/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Vista;

import SQL.crudsql;

/**
 *
 * @author mac
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btmConsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbPropietario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbPlaca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPiso = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lbMarca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbColor = new javax.swing.JTextField();
        jComboBoxPuesto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 34, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gurmukhi MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PARQUEO INTELIGENTE ULTRA 4K SMART");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 380, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/cubo-en-la-antartica_3840x2160_xtrafondos.com 2.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 50));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Puesto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/home_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton3.setText("VOLVER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 100, 40));

        btmConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btmConsultar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btmConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/search_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmConsultar.setText("AGREGAR");
        btmConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btmConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 110, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Piso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 20));

        lbPropietario.setBackground(new java.awt.Color(255, 255, 255));
        lbPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbPropietarioActionPerformed(evt);
            }
        });
        jPanel1.add(lbPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Propietario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        lbModelo.setBackground(new java.awt.Color(255, 255, 255));
        lbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbModeloActionPerformed(evt);
            }
        });
        jPanel1.add(lbModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Modelo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        lbPlaca.setBackground(new java.awt.Color(255, 255, 255));
        lbPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(lbPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 210, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Placa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 20));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro en vehiculo");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 540, 30));

        jComboBoxPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un piso", "A", "B", "C", "D", "E" }));
        jPanel1.add(jComboBoxPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 210, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Marca:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        lbMarca.setBackground(new java.awt.Color(255, 255, 255));
        lbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(lbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Color:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        lbColor.setBackground(new java.awt.Color(255, 255, 255));
        lbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbColorActionPerformed(evt);
            }
        });
        jPanel1.add(lbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 210, 30));

        jComboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un puesto", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        jPanel1.add(jComboBoxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    crudsql crup = new crudsql();
    private void btmConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmConsultarActionPerformed
        crup.insertar(jComboBoxPuesto.getSelectedItem().toString(),jComboBoxPiso.getSelectedItem().toString().toLowerCase(), lbMarca.getText(), lbModelo.getText(), lbPlaca.getText(), lbPropietario.getText(), lbColor.getText());
        lbMarca.setText("");
        lbColor.setText("");
        lbModelo.setText("");
        lbPlaca.setText("");
        lbPropietario.setText("");
        jComboBoxPiso.setSelectedIndex(0);
        jComboBoxPuesto.setSelectedIndex(0);
    }//GEN-LAST:event_btmConsultarActionPerformed

    private void lbPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbPropietarioActionPerformed

    private void lbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbModeloActionPerformed

    private void lbPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbPlacaActionPerformed

    private void lbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMarcaActionPerformed

    private void lbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmConsultar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxPiso;
    private javax.swing.JComboBox<String> jComboBoxPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lbColor;
    private javax.swing.JTextField lbMarca;
    private javax.swing.JTextField lbModelo;
    private javax.swing.JTextField lbPlaca;
    private javax.swing.JTextField lbPropietario;
    // End of variables declaration//GEN-END:variables
}
