/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Vista;
/**
 *
 * @author mac
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btmGestionUsuario = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();
        btmConsultarVehiculo = new javax.swing.JButton();
        btmEliminarVEHI = new javax.swing.JButton();
        btmRegistrarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 48, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Gurmukhi MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PARQUEO INTELIGENTE ULTRA 4K SMART");
        jPanel3.add(jLabel2);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/cubo-en-la-antartica_3840x2160_xtrafondos.com.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione su opcion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        btmGestionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btmGestionUsuario.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmGestionUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btmGestionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/search_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmGestionUsuario.setText("GESTION DE USUARIO");
        btmGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmGestionUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btmGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 190, 40));

        btmSalir.setBackground(new java.awt.Color(255, 255, 255));
        btmSalir.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmSalir.setForeground(new java.awt.Color(0, 0, 0));
        btmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/exit_to_app_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmSalir.setText("CERRAR SESION");
        btmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btmSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 190, 40));

        btmConsultarVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btmConsultarVehiculo.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmConsultarVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        btmConsultarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/search_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmConsultarVehiculo.setText("CONSULTAR VEHICULO");
        btmConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmConsultarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btmConsultarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 40));

        btmEliminarVEHI.setBackground(new java.awt.Color(255, 255, 255));
        btmEliminarVEHI.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmEliminarVEHI.setForeground(new java.awt.Color(0, 0, 0));
        btmEliminarVEHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmEliminarVEHI.setText("ELIMINAR VEHICULO");
        btmEliminarVEHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmEliminarVEHIActionPerformed(evt);
            }
        });
        jPanel1.add(btmEliminarVEHI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 40));

        btmRegistrarVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btmRegistrarVehiculo.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmRegistrarVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        btmRegistrarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/add_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmRegistrarVehiculo.setText("REGISTRAR VEHICULO");
        btmRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btmRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmGestionUsuarioActionPerformed
        GestioUsuario gu = new GestioUsuario();
        gu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btmGestionUsuarioActionPerformed

    private void btmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btmSalirActionPerformed

    private void btmConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmConsultarVehiculoActionPerformed
        Mapa map = new Mapa();
        map.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmConsultarVehiculoActionPerformed

    private void btmEliminarVEHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEliminarVEHIActionPerformed
        Eliminar eli = new Eliminar();
        eli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmEliminarVEHIActionPerformed

    private void btmRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegistrarVehiculoActionPerformed
        Agregar agre = new Agregar();
        agre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmRegistrarVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmConsultarVehiculo;
    private javax.swing.JButton btmEliminarVEHI;
    private javax.swing.JButton btmGestionUsuario;
    private javax.swing.JButton btmRegistrarVehiculo;
    private javax.swing.JButton btmSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
