/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Vista;

import SQL.crudsql;
import com.clases.Usuarios;

/**
 *
 * @author mac
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Usuarios usua = new Usuarios();
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbSalida = new javax.swing.JLabel();
        btmRegistrarse = new javax.swing.JButton();
        btmSalirl = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btmIngresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 48, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Gurmukhi MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PARQUEO INTELIGENTE ULTRA 4K SMART");
        jPanel3.add(jLabel2);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/cubo-en-la-antartica_3840x2160_xtrafondos.com.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        lbSalida.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbSalida.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(lbSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, 20));

        btmRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        btmRegistrarse.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        btmRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/add_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmRegistrarse.setText("REGISTRARSE");
        btmRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btmRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 130, 40));

        btmSalirl.setBackground(new java.awt.Color(255, 255, 255));
        btmSalirl.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmSalirl.setForeground(new java.awt.Color(0, 0, 0));
        btmSalirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/exit_to_app_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmSalirl.setText("SALIR");
        btmSalirl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalirlActionPerformed(evt);
            }
        });
        jPanel1.add(btmSalirl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 130, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 50, -1));

        lbusuario.setBackground(new java.awt.Color(255, 255, 255));
        lbusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(lbusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 20));

        btmIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btmIngresar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btmIngresar.setForeground(new java.awt.Color(0, 0, 0));
        btmIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Vista/imagen/logout_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btmIngresar.setText("INGRESAR");
        btmIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btmIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));

        lbContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegistrarseActionPerformed
        AgregarUsua agregar = new AgregarUsua();
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btmRegistrarseActionPerformed

    private void btmSalirlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirlActionPerformed
        dispose();
    }//GEN-LAST:event_btmSalirlActionPerformed

    private void lbusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbusuarioActionPerformed

    private void btmIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmIngresarActionPerformed
        crudsql crud = new crudsql();
        crud.buscarLogin(lbusuario.getText(), lbContraseña.getText());
        if (usua.getUsuario()==""){
            lbSalida.setText("Usuario o contraseña incorrecta");
        }else{
            dispose();
        }
    }//GEN-LAST:event_btmIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmIngresar;
    private javax.swing.JButton btmRegistrarse;
    private javax.swing.JButton btmSalirl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField lbContraseña;
    private javax.swing.JLabel lbSalida;
    private javax.swing.JTextField lbusuario;
    // End of variables declaration//GEN-END:variables
}
